### PR TITLE
fix QUART/MEDIAN/MIN/MAX on number/date/string

### LINKED ISSUE #411: MAX/MIN function not working for words
Apparently, using JSON table data, and aggregating the entire table into one record (no GROUP BY):
the SUM function works fine, but
the MAX/MIN functions return "undefined"
and the GREATEST/LEAST functions return 0.

Here is a sample of the data I use:

```
[ {field1: value1, field2:value2} ],
[ {fieldA: valueA, fieldB: valueB} ]
```

Am I doing something wrong or are the functions incomplete?

Thanks,
Timm

### PR DESCRIPTION
**Pull request by forestfang-stripe**
Fix MIN/MAX and GREATEST/LEAST to work on date and string by actively compare with `<` and `>` instead of `Math.min` and `Math.max`. This is commonly supported by other SQL engine: https://www.w3resource.com/sql/aggregate-functions/min-function.php
Currently, `MIN/MAX` works for Date but the data type changes to number, which is not what user would expect.

Fix QUART/MEDIAN to use custom comparator with `<` and `>`. When comparator is not supplied, Javascript coerce arguments to string:
>If omitted, the array elements are converted to strings, then sorted according to each character's Unicode code point value.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

Enabled skipped tests on these functions and update tests for new and correct behaviors (for example, median of numbers between 1 and 10000 should be 5000 not 5499.) add test from #104

p.s. some files got auto-formatted, specifically for `423groupby.js`, I only changed 'MIN' and 'MAX' implementation.

closes #411

### CODE REVIEW

File: src/423groupby.js [hunk 1]
```diff
@@ -319,41 +300,17 @@ if(false) {
...
-							pre +
-							"g['" +
-							colas +
-							"']=Math.max(g['" +
-							colas +
-							"']," +
-							colexp +
-							');' +
-							post
+							pre + 'if ((y=' + colexp + ") > g['" + colas + "']) g['" + colas + "'] = y;" + post
```
Comment (forestfang-stripe) [inline src/423groupby.js]: I used `y` here assuming it is intended to be a temporary variable (as far as I can tell from how it is used in `AVG`)

**Comment by mathiasrw** [comment]
You are soooo deep into the details. Wow. I love it. even a nice test case. Perfect.

**Comment by mathiasrw** [comment]
Released as version 0.5.4 💟
